# Generated by Django 3.0.6 on 2020-05-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.EmailField(db_index=True, max_length=150, unique=True)),
                ('email', models.EmailField(db_index=True, max_length=150, unique=True)),
                ('surname', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=15, null=True)),
                ('sign_in_method', models.CharField(choices=[('EMAIL', 'EMAIL'), ('GOOGLE', 'GOOGLE'), ('FACE_BOOK', 'FACE_BOOK'), ('TWITTER', 'TWITTER'), ('GITHUB', 'GITHUB'), ('APPLE', 'APPLE')], default='EMAIL', max_length=20)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
